### PR TITLE
Multilanguage translation

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by davidtakac** [comment]
This is amazing! Thank you so much. I'll check it out and merge first chance I get.

**Comment by noscirep** [comment]
I glanced over the Swedish translation and noticed several incorrectly translated strings. I would be happy to do a proper Swedish translation of this beautifully minimalistic weather app that I use every day. Where can I find the English source strings, and how do I submit the translation when it is done (I haven't really used GitHub before)?

**Comment by ghost** [comment]
> I glanced over the Swedish translation and noticed several incorrectly translated strings. I would be happy to do a proper Swedish translation of this beautifully minimalistic weather app that I use every day. Where can I find the English source strings, and how do I submit the translation when it is done (I haven't really used GitHub before)?

Please join here and feel free to fix stuff

https://crowdin.com/project/prognoza

**Comment by noscirep** [comment]
> > I glanced over the Swedish translation and noticed several incorrectly translated strings. I would be happy to do a proper Swedish translation of this beautifully minimalistic weather app that I use every day. Where can I find the English source strings, and how do I submit the translation when it is done (I haven't really used GitHub before)?
> 
> Please join here and feel free to fix stuff
> 
> https://crowdin.com/project/prognoza

Great, thank you!

**Comment by davidtakac** [comment]
I just tested this PR. The names of value directories which specify regions are incorrect. The region part must have an `r` prefix. 

- `values-zh-CN` should be `values-zh-rCN`
- `values-pt-PT` should be `values-pt-rPT`
- etc. 

I would correct this manually and merge, but this would have to be done for every PR. Does Crowdin allow you to specify the output format of the value directories?

**Comment by ghost** [comment]
I got health issues atm and won't do/fix stuff. You can apply at crowdin and I will make you guys proofreaders or project managers.

**Comment by davidtakac** [comment]
I'll do that. Get well soon!

**Comment by davidtakac** [comment]
@ryder203 I just created a Crowdin account with username `davidtakac` and joined the Prognoza project. When you get the chance, please give me the access I need to edit the output names of the resource directories :)

**Comment by davidtakac** [comment]
I couldn't figure out a way to change the export format of the directories in Crowdin. But I [documented the steps](https://github.com/davidtakac/prognoza/blob/dev/androidApp/STRINGS.md) to batch-rename them to the proper format. I'll probably make them into a script.

I also added a Translate section to the README so people know where to look.

Thank you again for the initiative to put these strings into Crowdin. I can't believe people contributed more than 20 translations :rocket: And thank you to everyone who contributed!

**Comment by davidtakac** [comment]
> I couldn't figure out a way to change the export format of the directories in Crowdin

I figured it out :smile: You need to create a bundle and there you can specify the format. No script required.

**Pull request closed without merging**
