### PR TITLE
edit traslate Ru

### PR DESCRIPTION
**Pull request by userkilled**
Nothing worthwhile came to mind.

### CODE REVIEW

**Comment by davidtakac** [comment]
Why the newline? The length seems comparable to "Feels like", so it should look fine on most screens.

**Comment by userkilled** [comment]
I'm just saying, for the future, for all screens. Now I've figured out the purpose 😅

**Comment by userkilled** [comment]
Screenshot_20230227

Screenshot_20230227


Now, 3.4.1. Orientation.

**Comment by davidtakac** [comment]
If you're referring to the text being on one line when horizontal and on two when vertical, this is expected behavior :) It only wraps to newline when there's no room

**Pull request closed without merging**
